apiVersion: v1
kind: Service
metadata:
  name: termix-lb
  namespace: termix
  labels:
    app: termix
  annotations:
    service.beta.kubernetes.io/managed-loadbalancer-plan: k8s-lb
    service.beta.kubernetes.io/managed-loadbalancer-backend-protocol: http
    service.beta.kubernetes.io/managed-loadbalancer-ssl-mode: letsencrypt
    service.beta.kubernetes.io/managed-loadbalancer-ssl-domain: termix.qovic.com
    service.beta.kubernetes.io/managed-loadbalancer-ssl-redirect: "true"
    service.beta.kubernetes.io/managed-loadbalancer-health-check-path: /health
spec:
  type: LoadBalancer
  selector:
    app: termix
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
