apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: termix-data
  namespace: termix
  labels:
    app: termix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
